name: Execute build order

on:
  workflow_call:

jobs:
  linux_build:
    runs-on: ubuntu-24.04
    name: Build Linux package
    steps:
      - name: Download conan.lock
        uses: actions/download-artifact@v4
        with:
          name: conan.lock
      - name: build package
        run: |
          conan create . --build="missing:mathlib/*" -pr=linux --lockfile=conan.lock --format=json > graph.json

